/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedFailuresRouteImport } from './routes/_authenticated/failures'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as ApiPublicResendOpenersRouteImport } from './routes/api/public/resend-openers'
import { Route as ApiPublicManychatWebhookRouteImport } from './routes/api/public/manychat-webhook'
import { Route as ApiPublicFollowupsRouteImport } from './routes/api/public/followups'
import { Route as ApiPublicBookingRemindersRouteImport } from './routes/api/public/booking-reminders'
import { Route as AuthenticatedConversationsIdRouteImport } from './routes/_authenticated/conversations.$id'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFailuresRoute = AuthenticatedFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicResendOpenersRoute = ApiPublicResendOpenersRouteImport.update({
  id: '/api/public/resend-openers',
  path: '/api/public/resend-openers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManychatWebhookRoute =
  ApiPublicManychatWebhookRouteImport.update({
    id: '/api/public/manychat-webhook',
    path: '/api/public/manychat-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFollowupsRoute = ApiPublicFollowupsRouteImport.update({
  id: '/api/public/followups',
  path: '/api/public/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingRemindersRoute =
  ApiPublicBookingRemindersRouteImport.update({
    id: '/api/public/booking-reminders',
    path: '/api/public/booking-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConversationsIdRoute =
  AuthenticatedConversationsIdRouteImport.update({
    id: '/conversations/$id',
    path: '/conversations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/failures': typeof AuthenticatedFailuresRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/api/public/booking-reminders': typeof ApiPublicBookingRemindersRoute
  '/api/public/followups': typeof ApiPublicFollowupsRoute
  '/api/public/manychat-webhook': typeof ApiPublicManychatWebhookRoute
  '/api/public/resend-openers': typeof ApiPublicResendOpenersRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/failures': typeof AuthenticatedFailuresRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/api/public/booking-reminders': typeof ApiPublicBookingRemindersRoute
  '/api/public/followups': typeof ApiPublicFollowupsRoute
  '/api/public/manychat-webhook': typeof ApiPublicManychatWebhookRoute
  '/api/public/resend-openers': typeof ApiPublicResendOpenersRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/failures': typeof AuthenticatedFailuresRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/api/public/booking-reminders': typeof ApiPublicBookingRemindersRoute
  '/api/public/followups': typeof ApiPublicFollowupsRoute
  '/api/public/manychat-webhook': typeof ApiPublicManychatWebhookRoute
  '/api/public/resend-openers': typeof ApiPublicResendOpenersRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/appointments'
    | '/dashboard'
    | '/failures'
    | '/clients/$id'
    | '/clients/new'
    | '/conversations/$id'
    | '/api/public/booking-reminders'
    | '/api/public/followups'
    | '/api/public/manychat-webhook'
    | '/api/public/resend-openers'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/appointments'
    | '/dashboard'
    | '/failures'
    | '/clients/$id'
    | '/clients/new'
    | '/conversations/$id'
    | '/api/public/booking-reminders'
    | '/api/public/followups'
    | '/api/public/manychat-webhook'
    | '/api/public/resend-openers'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/failures'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/_authenticated/conversations/$id'
    | '/api/public/booking-reminders'
    | '/api/public/followups'
    | '/api/public/manychat-webhook'
    | '/api/public/resend-openers'
    | '/_authenticated/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBookingRemindersRoute: typeof ApiPublicBookingRemindersRoute
  ApiPublicFollowupsRoute: typeof ApiPublicFollowupsRoute
  ApiPublicManychatWebhookRoute: typeof ApiPublicManychatWebhookRoute
  ApiPublicResendOpenersRoute: typeof ApiPublicResendOpenersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/failures': {
      id: '/_authenticated/failures'
      path: '/failures'
      fullPath: '/failures'
      preLoaderRoute: typeof AuthenticatedFailuresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/resend-openers': {
      id: '/api/public/resend-openers'
      path: '/api/public/resend-openers'
      fullPath: '/api/public/resend-openers'
      preLoaderRoute: typeof ApiPublicResendOpenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manychat-webhook': {
      id: '/api/public/manychat-webhook'
      path: '/api/public/manychat-webhook'
      fullPath: '/api/public/manychat-webhook'
      preLoaderRoute: typeof ApiPublicManychatWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/followups': {
      id: '/api/public/followups'
      path: '/api/public/followups'
      fullPath: '/api/public/followups'
      preLoaderRoute: typeof ApiPublicFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-reminders': {
      id: '/api/public/booking-reminders'
      path: '/api/public/booking-reminders'
      fullPath: '/api/public/booking-reminders'
      preLoaderRoute: typeof ApiPublicBookingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversations/$id': {
      id: '/_authenticated/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof AuthenticatedConversationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFailuresRoute: typeof AuthenticatedFailuresRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedConversationsIdRoute: typeof AuthenticatedConversationsIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFailuresRoute: AuthenticatedFailuresRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedConversationsIdRoute: AuthenticatedConversationsIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBookingRemindersRoute: ApiPublicBookingRemindersRoute,
  ApiPublicFollowupsRoute: ApiPublicFollowupsRoute,
  ApiPublicManychatWebhookRoute: ApiPublicManychatWebhookRoute,
  ApiPublicResendOpenersRoute: ApiPublicResendOpenersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
